name: tester
on: [push]
jobs:
  test:
    name: runner / gotest
    runs-on: ubuntu-latest
    container: ghcr.io/runatlantis/testing-env:805e94e7f648eddb0484e539a7b51410d39529bc
    steps:
      # user in image needs write access to do anything
      - name: setup
        run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - uses: actions/checkout@v3
      - run: make test-all